### ISSUE TITLE
Unable to get Clients in a Room

### ISSUE THREAD

**Issue by avirati** [lemonde/primus-cluster#19]
Hi,
I am using primus-emit and primus-rooms. I have added primus-cluster after these two. However, the following code does not seem to work. 

```
primus.room(room_id).clients(function (err, spark_ids) {
  console.log(spark_ids);
})
```

It seems that the callback is never executed. I did take a peek in primus-rooms-adapter and found out that the callback is executed under process.nextTick : 

```
Adapter.prototype.clients = function clients(room, fn) {
  var _room = this.rooms[room]
    , ids = _room ? Object.keys(_room) : [];

  if (fn) process.nextTick(function tick() {
    fn(null, ids);
  });
  return ids;
};
```

I then changed the code in lib/adapter.js from : 

```
Adapter.prototype.clients = function clients(room, cb) {
  var roomKeys = this._getRoomKeys(room)
  this.client.sunion(roomKeys, cb);
};
```

to

```
Adapter.prototype.clients = function clients(room, cb) {
  var roomKeys = this._getRoomKeys(room);
  process.nextTick(function(){
    this.client.sunion(roomKeys, cb);
  });
};

```

In this case, the callback does get executed but I get empty array. Any thing I might be missing here ? Any help / hint would be greatly appreciated :)

Avinash

**Comment by gregberge** [comment]
Outdated
