### ISSUE TITLE
Send a message to a specific user on an other instance

### ISSUE THREAD

**Issue by rodincave** [lemonde/primus-cluster#3]
Hi,

I am wondering if there is possibility to use this plugin to send 1-to-1 messages from one user1 on server1 to user2 on server2 ?
I installed the plugin with redis-rooms and redis-emitter. I saw how to broadcast a message to an entier room, but is there a way to send it to only one specific socket in a room ?

Thanks

**Comment by SeyZ** [comment]
:+1: for this feature request

**Comment by davidlondono** [comment]
I thought I could send a event to a spark by using
```
 primus.spark(sparkId)
```
but it only return a spark if exist on that cluster

**Comment by PedroMD** [comment]
@neoziro, I know this issue is closed, but did you really end up adding support for this as you've previously mentioned?
